### ISSUE TITLE
Installing project and running yarn ios causes Iphone simulator to fail with exception "Tried to register two view with the same name RNSVGRect"

### ISSUE THREAD

**Issue by yaruno** [cawfree/create-react-native-dapp#11]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Installation completes correctly by running npx create-react-native-dapp but running the project after installation causes an exception.

Node v15.3.0
NPM 7.0.14
MacOS 10.15.3

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

<img width="431" alt="Screenshot 2021-08-10 at 13 23 08" src="https://user-images.githubusercontent.com/3228613/128851339-008d9543-a385-4915-9ce8-ffe6ad9fadb7.png">
<img width="715" alt="Screenshot 2021-08-10 at 13 23 25" src="https://user-images.githubusercontent.com/3228613/128851346-0f7b707d-779b-4de4-8545-8a3b5192a3c8.png">
<img width="429" alt="Screenshot 2021-08-10 at 13 23 13" src="https://user-images.githubusercontent.com/3228613/128851847-b030f0e6-e4ff-405e-af9d-4192f0942c74.png">

**Comment by yaruno** [comment]
Issues seems similar to this one https://github.com/WalletConnect/walletconnect-monorepo/issues/569

**Comment by Conrador** [comment]
I have the same issue.I tried to remove react-native-svg from @walletconnect node_modules but error still appears.

**Comment by cawfree** [comment]
Hey, apologies for the delay in getting back to you both on this issue. I'm introducing an update for a [recent bump](https://www.npmjs.com/package/@walletconnect/react-native-dapp/v/1.6.1) over the next hour, and whilst I'm here I'll try to patch an ad-hoc fix for this issue and open a PR to resolve this issue on the dependency.

Thanks for your patience.

**Comment by cawfree** [comment]
Replicated. 👍

**Comment by cawfree** [comment]
This issues been fixed in [__1.2.18__](https://www.npmjs.com/package/create-react-native-dapp/v/1.2.18).
