### ISSUE TITLE
Stuck during initialisation

### ISSUE THREAD

**Issue by simibac** [cawfree/create-react-native-dapp#2]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

installer is stuck in `Locating project files.` as shown in the image
<img width="725" alt="Screenshot 2021-01-03 at 21 19 54" src="https://user-images.githubusercontent.com/15369592/103487984-76d0ce00-4e09-11eb-89ca-7f34788b92a5.png">

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

using npm 7.0.3, npx 7.0.8, macos 11.1

**Comment by cawfree** [comment]
Thank you so much for your bug report. 🙏 I will look into this and get
back to you as soon as possible.

**Comment by cawfree** [comment]
Can I just check that you're able to run `npx create-react-native-app` with no error?

**Comment by cawfree** [comment]
[This](https://github.com/expo/create-react-native-app/issues/837) looks like the fix. :)

> Fixed using nvm (node version manager) and switching to node version 12
