### ISSUE TITLE
createNativeStackNavigator from '@react-navigation/native-stack' giving error

### ISSUE THREAD

**Issue by daboigbae** [cawfree/create-react-native-dapp#20]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I may be doing something wrong, but when I run the application created by `create-react-native-dapp` everything works fine. I am able to connect and all, no problem. 

However, the moment I try to run `createNativeStackNavigator` to create some navigations and screen changes, I get the following error: 

`Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider`

What am I doing wrong? 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Here are my dependencies

"dependencies": {
    "@react-native-async-storage/async-storage": "1.13.4",
    "@react-native-community/checkbox": "^0.5.9",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@walletconnect/react-native-dapp": "1.6.1",
    "axios": "^0.24.0",
    "base-64": "1.0.0",
    "buffer": "6.0.3",
    "expo": "~42.0.0",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.8.1",
    "node-libs-browser": "2.2.1",
    "path-browserify": "0.0.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-hook-form": "^7.18.0",
    "react-native": "~0.63.4",
    "react-native-crypto": "2.2.0",
    "react-native-deck-swiper": "^2.0.5",
    "react-native-dotenv": "2.4.3",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-get-random-values": "1.5.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localhost": "1.0.0",
    "react-native-paper": "^4.9.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "~3.4.0",
    "react-native-stream": "0.1.9",
    "react-native-svg": "9.6.4",
    "react-native-unimodules": "0.14.10",
    "react-native-vector-icons": "^9.0.0",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.0",
    "web3": "1.3.1"
  },

**Comment by cawfree** [comment]
Please see [this issue](https://github.com/th3rdwave/react-native-safe-area-context/issues/110).
