### ISSUE TITLE
Running yarn:android make some changes into the application

### ISSUE THREAD

**Issue by blixit** [cawfree/create-react-native-dapp#23]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
I'm trying to run the android app.

I ran yarn:android which updated the package.json and added an android folder.

This behavior is a little disturbing. It's like I ejected something. Can you tell me is this is the intended behavior ?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Local Context:

MacOS 12
node 12 (by the way, it should be explicit in the readme)
yarn 1.22.10
expo 4.13.0

| launching on device | changes |
| :---: | :---: |
| <img width="400" alt="image" src="https://user-images.githubusercontent.com/6025710/141379732-9445d69a-d1b2-4449-a15b-ff747924ae37.png"> | <img width="600" alt="image" src="https://user-images.githubusercontent.com/6025710/141379986-1d8f7e0a-da9c-4589-a0b8-d8d82e852e2b.png">  |

**Comment by benjaminharringtonrose** [comment]
I experienced this same issue when running `yarn ios`, which runs `scripts/ios`. This package is awesome though! However I've been stuck on this for a week now.. I have a strong feeling it has something to do with our expo version

**Comment by cawfree** [comment]
You are correct that the application is ejected from Expo when executed for the first time; this is because it depends upon native libraries not currently supported by Expo's stack.
