### ISSUE TITLE
Can you develop for react-native-cli, i think cli is popular for developer and it work better than expo !!!

### ISSUE THREAD

**Issue by minhnndev** [cawfree/create-react-native-dapp#27]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by cawfree** [comment]
Completely agreed. The whole ejection step is causing developers a lot of headaches.

I was wondering if we should just go full throttle and just implement for [universal]( https://github.com/mmazzarolo/react-native-universal-monorepo) apps. We could finish off support for all platforms this way and start a Web3 revolution.

Easiest of all, we could just move into a monorepo and just have the cli act as a thin git clone, I don’t think it’s scaling the way we need it to going forward.
