### ISSUE TITLE
Wallet Connect Integration

### ISSUE THREAD

**Issue by simibac** [cawfree/create-react-native-dapp#4]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Would be great to have an option to have walletconnect integrated automatically.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by cawfree** [comment]
Hey @simibac! 👋 Hope you’ve been doing well!

Sorry for the delay in getting back to you. I’ve been mulling this over for the past couple of days. 😂

WalletConnect was one of the first things I wanted to integrate as an optional extension, and I agree, it would be an extremely cool feature!

I have yet to figure out what form it would take. There’s a couple of routes we could go down and I’d be interested in hearing which one you think would be best.

I think I’m the spirit of the repo, it should be a WalletConnect instance which can be used as a web3 provider, but one of my friends has hit some difficult roadblocks getting the two to play nicely on native. But this could be a problem we are supposed to solve.

Then there’s the standard react native SDK, which I’m not sure is compatible with web3 directly, but it’s the most obvious to use. I would hope it’d be as simple as just installing manually, but then I’d wonder what problems we’d be solving. 😅

I’ll do some experimentation and see what seems best/most feasible. But if you have a specific idea of how this should be done, I’d love to hear about it!

**Comment by cawfree** [comment]
This is currently [**In Progress**](https://github.com/WalletConnect/walletconnect-monorepo/pull/413). Thanks for your patience!

**Comment by cawfree** [comment]
Hey @simibac, the package is now available [**here**](https://www.npmjs.com/package/@walletconnect/react-native-dapp)!

I will be publishing a default integration with `create-react-native-dapp` tonight 🙏

**Comment by cawfree** [comment]
[**1.2.4**](https://www.npmjs.com/package/create-react-native-dapp/v/1.2.4)

Thanks for your patience! Have fun!
