### ISSUE TITLE
Broken app when creating fresh project

### ISSUE THREAD

**Issue by gregjw** [cawfree/create-react-native-dapp#7]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I'm getting two lots of errors relating to your automated use of expo, see screenshots below:
[https://imgur.com/a/gtKBBKo](https://imgur.com/a/gtKBBKo)

After fixing those issues by adding those fields in `app.json`, I get this issue and googling it yields no useful results at all.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

N/A

**Comment by cawfree** [comment]
Hey @gregjw, apologies for the delay in getting back to you!

It looks like this might be associated with the version of `expo-cli` that's running on your development machine. I can confirm this works against `4.0.17`, if you run `npx expo-cli --version`, do you see something less than this?

**Comment by gregjw** [comment]
Yup, that was it!  I was on 3.11.9.  

Yarn hadn't correctly updated it, had to manually delete the old version.

Thanks Alex.

**Comment by cawfree** [comment]
Great to hear. Best of luck! 🚀

**Comment by DeveloperAlly** [comment]
FYI I had to use npm install --legacy-peer-deps flag to run. 
May help others -thanks for all the work in this! 
Mobile Web3 is so lacking dev tools!
